name: Playwright Tests
permissions:
  contents: write
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm test
      continue-on-error: true

    # Install Allure CLI Manually
    - name: Install Allure CLI
      run: |
        ALLURE_VERSION=2.20.1
        curl -o allure-$ALLURE_VERSION.tgz -L https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
        tar -zxvf allure-$ALLURE_VERSION.tgz
        sudo mv allure-$ALLURE_VERSION /opt/allure
        # Check if Allure is installed
        ls -la /opt/allure/bin
        # Make sure the Allure binary is executable
        sudo chmod +x /opt/allure/bin/allure
        # Add Allure to PATH
        echo "/opt/allure/bin" >> $GITHUB_PATH
        # Check if Allure is accessible
        source $GITHUB_ENV
        echo "Allure version:"
        allure --version  # Check if allure is accessible

    # Ensure Allure report generation step always runs
    - name: Check allure-results Directory
      run: |
        echo "Checking for allure-results directory..."
        if [ -d allure-results ]; then
          echo "allure-results exists."
          ls -la allure-results
        else
          echo "allure-results does not exist."
        fi

    - name: Generate Allure Report
      run: |
        echo "Generating Allure report..."
        if [ -d allure-results ]; then
          allure generate allure-results --clean -o allure-report
        else
          echo "Cannot generate report, allure-results not found."
        fi
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}

    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    # Conditional copying and deleting of allure report directory
    - name: Copy Allure Report to gh-pages branch
      run: |
        echo "Copying Allure report to gh-pages branch..."
        if [ -d allure-report ]; then
          echo "Copying Allure report..."
          mkdir -p ./allure-report/
          cp -r allure-report/* ./allure-report/ || echo "No allure report generated to copy."
        else
          echo "No allure-report directory found."
        fi

    - name: Debug List contents of Allure Report
      run: ls -la allure-report || echo "allure-report directory does not exist."

    - name: Commit and Push Allure Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add allure-report/
        git status   # This will show if there are any changes to commit
        git commit -m "Update Allure report" || echo "No changes to commit"
        git push origin gh-pages

    - name: Confirm GitHub Pages Setup
      run: echo "GitHub Pages is set up on the 'gh-pages' branch."
