name: Playwright Tests
permissions:
  contents: write
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - uses: actions/checkout@v4

    # Step 2: Setup Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Step 5: Run Playwright tests
    - name: Run Playwright tests
      run: npm test
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
      continue-on-error: true

    # Step 6: Install Allure
    - name: Install Allure
      run: |
        ALLURE_VERSION=2.20.1
        curl -o allure-$ALLURE_VERSION.tgz -L https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
        tar -zxvf allure-$ALLURE_VERSION.tgz
        sudo mv allure-$ALLURE_VERSION /opt/allure
        sudo chmod +x /opt/allure/bin/allure
        echo "/opt/allure/bin" >> $GITHUB_PATH
      shell: /usr/bin/bash -e {0}

    # Step 7: Ensure allure-results/history directory exists before generating the report
    - name: Ensure Allure History Directory
      run: mkdir -p allure-results/history

    # Step 8: Restore Allure History (if exists)
    - name: Download Allure History Artifact
      uses: actions/download-artifact@v4  # Updated to v4 for Node.js 20 compatibility
      with:
        name: allure-history
        path: allure-results/history
      continue-on-error: true  # Continue even if history is missing

    # Step 9: Generate Allure Report with History
    - name: Generate Allure Report
      run: |
        echo "Generating Allure report..."
        if [ -d allure-results ]; then
          /opt/allure/bin/allure generate allure-results --clean -o allure-report
        else
          echo "Cannot generate report, allure-results not found."
        fi

    # Step 10: Debug: Check Allure History after Test Execution
    - name: Debug Allure History Directory
      run: |
        echo "Listing contents of allure-results/history:"
        ls -la allure-results/history || echo "allure-results/history directory does not exist."

    # Step 11: Save Allure report as artifact to avoid loss during branch switching
    - name: Save Allure Report as Artifact
      uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 compatibility
      with:
        name: allure-report
        path: allure-report

    # Step 12: Save Allure History for Trend Data
    - name: Save Allure History as Artifact
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: allure-history
        path: allure-results/history
        if-no-files-found: warn  # Warn but don't fail if no history files are found

    # Step 13: Checkout gh-pages branch
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    # Step 14: Restore the Allure report from artifact
    - name: Download Allure Report Artifact
      uses: actions/download-artifact@v4  # Updated to v4 for Node.js 20 compatibility
      with:
        name: allure-report
        path: ./allure-report

    # Step 15: Copy the Allure report to the gh-pages branch
    - name: Copy Allure Report to gh-pages
      run: |
        if [ -d allure-report ]; then
          mkdir -p ./allure-report/
          cp -r allure-report/* ./allure-report/ || echo "No allure report generated to copy."
        else
          echo "No allure-report directory found to copy."
        fi

    # Step 16: List contents of allure-report before git commit
    - name: Debug List Allure Report Before Commit
      run: |
        echo "Listing contents of allure-report before commit:"
        ls -la allure-report || echo "allure-report directory does not exist."

    # Step 17: Commit and push the report to the gh-pages branch
    # Commit and push the report to the gh-pages branch
    - name: Commit and Push Allure Report
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      if [ -d allure-report ]; then
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add allure-report/
        git commit -m "Update Allure report" || echo "No changes to commit"
        git push origin gh-pages
      else
        echo "No allure-report directory to commit."
      fi  # <-- This closes the 'if' block correctly

    # Step 18: Confirm GitHub Pages Setup
    - name: Confirm GitHub Pages Setup
      run: echo "GitHub Pages is set up on the 'gh-pages' branch."
