name: Playwright Tests
permissions:
  contents: write
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm test
      continue-on-error: true

    # Allure Installation (same as before)
    - name: Install Allure
      run: |
        ALLURE_VERSION=2.20.1
        curl -o allure-$ALLURE_VERSION.tgz -L https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
        tar -zxvf allure-$ALLURE_VERSION.tgz
        sudo mv allure-$ALLURE_VERSION /opt/allure
        ls -la /opt/allure/bin
        sudo chmod +x /opt/allure/bin/allure
        echo "/opt/allure/bin" >> $GITHUB_PATH
      shell: /usr/bin/bash -e {0}

    # Generate Allure Report
    - name: Generate Allure Report
      run: |
        echo "Generating Allure report..."
        if [ -d allure-results ]; then
          /opt/allure/bin/allure generate allure-results --clean -o allure-report
        else
          echo "Cannot generate report, allure-results not found."
        fi
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}

    # Ensure Allure report is generated and check allure-results directory
    - name: Check Allure Results Directory
      run: |
        if [ -d allure-results ]; then
          echo "allure-results exists. Listing contents:"
          ls -la allure-results
        else
          echo "allure-results does not exist."
        fi

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    # Copy the Allure report to the gh-pages branch
    - name: Copy Allure Report to gh-pages
      run: |
        echo "Copying Allure report to gh-pages branch..."
        if [ -d allure-report ]; then
          mkdir -p ./allure-report/
          cp -r allure-report/* ./allure-report/ || echo "No allure report generated to copy."
        else
          echo "No allure-report directory found."
        fi

    # Debug step to list contents of allure-report
    - name: Debug List Allure Report
      run: ls -la allure-report || echo "allure-report directory does not exist."

    # Commit and push the report to the gh-pages branch
    - name: Commit and Push Allure Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add allure-report/
        git commit -m "Update Allure report" || echo "No changes to commit"
        git push origin gh-pages

    - name: Confirm GitHub Pages Setup
      run: echo "GitHub Pages is set up on the 'gh-pages' branch."
