name: Playwright Tests
permissions:
  contents: write
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        EMAIL: ${{ secrets.EMAIL }}
      continue-on-error: true

    # Generate Allure Report
    - name: Generate Allure Report
      if: always()
      run: npm run allure-report

    # Upload Playwright test results as artifact (optional, if needed)
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-test-results
        path: test-results/

    # Get Allure history from the gh-pages branch to retain trends
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # Use Allure Report Action from Marketplace to handle report generation and history
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: gh-pages/allure-history  # Reuse history from gh-pages
        keep_reports: 20  # Keep the last 20 reports for trend analysis

    # Deploy Allure report with history to GitHub Pages
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: gh-pages/allure-history  # Save report and history to gh-pages
